name: Action Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read nodejs version from package.json
        run: |
          echo "NODE_VERSION=$(node -p -e "require('./package.json').engines.node")" >> $GITHUB_ENV

      - name: Setup Node.js version ${{ env.PROJECT_NODE_VERSION }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ env.PROJECT_NODE_VERSION }}

      - name: Install dependencies and compile code
        run: |
          npm ci
          npm run build

      - name: Set some branch-based environment variables
        uses: ./
        with:
          KITCHEN_SINK: |
            master:value for KITCHEN_SINK on the master branch
            test-branch:value for KITCHEN_SINK on test-branch
            !pr:KITCHEN_SINK value for a pull request
            !pr|master:value for master PR
            release_candidate_*:KITCHEN_SINK Release Candidate
            !tag:KITCHEN_SINK value for a tag
            !default:default value for KITCHEN_SINK
          COMMENT_EMPTY_LINE_TEST: |
            !default:COMMENT_EMPTY_LINE_TEST
            # this is a comment


            # those are some empty, empty lines
          SECRET_TEST: |
            master:${{ secrets.TEST_SECRET }}
            !default:${{ secrets.TEST_SECRET}} but its default
          STATIC_TEST: 'just a static env var here'
          MASTER_PR: |
            !pr|master:value for master PR
            !default:default value for MASTER_PR
          TRIM_TEST: |
            branch-pr :value for branch-pr PR (trim)
            master :value for master merge (trim)
            !default:default value for MASTER_PR
            !pr|master :value for master PR (trim)

      - name: Print out those variables!
        run: |
          echo "KITCHEN_SINK: $KITCHEN_SINK"
          echo "COMMENT_EMPTY_LINE_TEST: $COMMENT_EMPTY_LINE_TEST"
          echo "SECRET_TEST: $SECRET_TEST"
          echo "STATIC_TEST: $STATIC_TEST"
          echo "MASTER_PR: $MASTER_PR"
          echo "TRIM_TEST: $TRIM_TEST"
